name: Publish NuGet Package

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'sparrow-cert/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8' # Adjust the version to your needs

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # - name: Run tests
      #   run: dotnet test --no-restore --verbosity normal

      - name: Pack the NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish to nuget.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json